.PHONY: part1
part1:
	ag -l . ../ | entr -s 'go run part1/main.go < input.txt'

.PHONY: part1-test
part1-test:
	ag -l . ../ | entr -s 'go run part1/main.go < test_input.txt'

.PHONY: part2
part2:
	ag -l . ../ | entr -s 'go run part2/main.go < input.txt'

.PHONY: part2-test
part2-test:
	ag -l . ../ | entr -s 'go run part2/main.go < test_input.txt'

